### ISSUE TITLE
Carrot documentation (Spelling/Typos)

### ISSUE THREAD

**Issue by MilanVojnovic95** [carrot-kpi/erc20-kpi-token-template#106]
This is issue that will address all spelling mistakes or typos in our documentation.

### Oracles

There was a spelling mistake in the sentence "Generally speaking, oracles are entities that connect a certain smart contract to external systems, making it able to access real-world data and implement logic that relies on that." The correct wording is "making it able to access real-world data and implement logic that relies on it." The word "that" should be replaced with "it" to make the sentence grammatically correct.

![Image](https://user-images.githubusercontent.com/57331244/235717715-c08239e1-27d7-4073-b066-d5a6aaa5692c.png)

### ERC20

"colleteral" should be spelled as "collateral".

![Image](https://user-images.githubusercontent.com/57331244/235720513-31aaa82f-1fe9-4d35-8317-7294e0c9f4d1.png)

### Creation / Oracle Configuration 

There is a spelling mistake in the sentence "Once you're satisfied with the oralce configuration click the "next" button." The word "oralce" should be corrected to "oracle".

![Image](https://user-images.githubusercontent.com/57331244/235721817-9b0bda71-021e-49a3-996c-ddf8014c40e2.png)

**Comment by luzzif** [comment]
These issues got addressed in commit f45e4267ace31485f3e4884fc163a30869a0ffee
