### ISSUE TITLE
Oracle finalization issue

### ISSUE THREAD

**Issue by guerrap** [carrot-kpi/erc20-kpi-token-template#193]
When running the local playground alongside the `defillama-answerer`, the finalization task fails every time for some reason with a generic `revert` error when estimating the gas.
The point of failure is the following (`defillama-answerer`):

```rs
match signer.fill_transaction(&mut call.tx, None).await {
    Ok(()) => {}
    Err(error) => {
        tracing::error!("could not fill answer call: {:#}", error);
        return Ok(());
    }
};
```

**Comment by luzzif** [comment]
Personally tried locally and had no issue at all. Please try again with the new answerer config I've given you locally and see if the issue persists
