### ISSUE TITLE
Clicking next on the campaign creation step 1 should make next step centered

### ISSUE THREAD

**Issue by Diogomartf** [carrot-kpi/erc20-kpi-token-template#33]
Currently when clicking next on the first step on the campaign creation the scroll is offset. (see image bellow).

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/5664434/218536380-d3d5c14d-174e-4aef-8b02-5e34ba0eea15.png">

**Comment by luzzif** [comment]
This should not be a thing anymore
