### ISSUE TITLE
opening date is required to be after current time, should display an error when it isn't

### ISSUE THREAD

**Issue by Diogomartf** [carrot-kpi/erc20-kpi-token-template#34]
it should display error when the bellow current time. Otherwise I don't know what I have to fix.

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/5664434/218552275-ffe0ed78-47e4-4215-affc-b18be36eeb07.png">

**Comment by luzzif** [comment]
This should be opened in the oracle template repo
