### ISSUE TITLE
Add description to fields to give more info on what is the field about

### ISSUE THREAD

**Issue by Diogomartf** [carrot-kpi/erc20-kpi-token-template#36]
We should add more info on what are the fields.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/5664434/218557523-db5d56a2-c177-4221-ad3e-25b752c338a5.png">

Maybe add a description under the label or a tooltip. A prefer the former.

**Comment by luzzif** [comment]
Should do this in the oracle template
