### ISSUE TITLE
More spacing between collateral 

### ISSUE THREAD

**Issue by Diogomartf** [carrot-kpi/erc20-kpi-token-template#37]
I would add more space between collateral, or maybe a divider, feels that they are very close.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/5664434/218594439-15aa0d7c-719d-420b-843e-aac97c2c4f99.png">

**Comment by luzzif** [comment]
Should be addressed in https://github.com/carrot-kpi/erc20-kpi-token-template/pull/54
