### ISSUE TITLE
No feedback when campaign is created

### ISSUE THREAD

**Issue by Diogomartf** [carrot-kpi/erc20-kpi-token-template#41]
When I did the transaction to create a campaign it stayed on the same page while giving no feedback.

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/5664434/218611700-2e89a473-d01f-4280-ad6a-4403cbee0614.png">

It should show feedback that the campaign was created and probably navigate to "campaign page".

**Comment by luzzif** [comment]
Should be addressed by https://github.com/carrot-kpi/erc20-kpi-token-template/pull/60
