### ISSUE TITLE
Input for ERC 20 token symbol should not accept emojis, strange chars, etc. 

### ISSUE THREAD

**Issue by Diogomartf** [carrot-kpi/erc20-kpi-token-template#51]
ERC 20 token symbol should not accept at least emojis as symbol (we have to check the specification for the name format).

<img width="288" alt="image" src="https://user-images.githubusercontent.com/5664434/221600749-81fc6f59-9040-4669-95bb-499e3dc3fcd8.png">

**Comment by luzzif** [comment]
Maybe someone wants to have an emoji, it would be possible I think
