### ISSUE TITLE
WalletConnect (unexpected behavior)

### ISSUE THREAD

**Issue by MilanVojnovic95** [carrot-kpi/erc20-kpi-token-template#66]
- By clicking on this button, WalletConnect automatically selects the address that is connected to my Ledger device, even though it is not currently connected, but there is only a connection between it and metamask, I am not sure how expected this behavior is, because I know that on Swapr, when I click on the WalletConnect option, I get a modal a window where I can choose which wallet to use.

![Image](https://user-images.githubusercontent.com/57331244/226588988-ea128d46-3723-49d8-8c53-eb5ec8e4962a.png)

As an example, on Swapr clicking the same button opens a modal window like this one with options:

![Image](https://user-images.githubusercontent.com/57331244/226589234-badb9518-c377-45f2-81b3-d49610e19e0b.png)

![Image](https://user-images.githubusercontent.com/57331244/226589291-8c504695-4ee7-4b2f-91a5-6dac0a639a93.png)

**Comment by guerrap** [comment]
When I click on `Wallet Connect` I get the expected modal, can you test it again? What are the steps to reproduce this behavior?

**Comment by guerrap** [comment]
When I click on `Wallet Connect` I get the expected modal, can you test it again? What are the steps to reproduce this behavior?

**Comment by MilanVojnovic95** [comment]
Retested, bug fixed.
