### ISSUE TITLE
KPI token expiration shouldn't allow submitting new answers

### ISSUE THREAD

**Issue by MilanVojnovic95** [carrot-kpi/erc20-kpi-token-template#80]
How to reproduce:

1. Create campaign with some minimum payouts.
2. Then go to created campaign and don’t give an answer until time left is 00 00 00

![Image](https://user-images.githubusercontent.com/57331244/227592162-f35cc3d5-663e-4c14-9129-a240bb42e324.png)

3. Even if campaign is exipred you are able to submit an answer 

![Image](https://user-images.githubusercontent.com/57331244/227592456-e550a416-ab54-44ff-ab3c-5b64ef0e4675.png)

There should be some error message so user would be aware that 
once KPI token (campaign) expires it's done, no more changes allowed...there is no possibility of giving an answer.

**Comment by guerrap** [comment]
The use should still be able to post new questions, but he should be aware that they won't affect anymore the outcome of the KPI token.
