### ISSUE TITLE
Oracle Answer Bond bug "."

### ISSUE THREAD

**Issue by MilanVojnovic95** [carrot-kpi/erc20-kpi-token-template#89]
When user goes to certain campaign and answer question, and then set "." as bond then we have error message. 

![Image](https://user-images.githubusercontent.com/57331244/228849152-55417781-7ff6-4037-9579-21a122744222.png)

![Image](https://user-images.githubusercontent.com/57331244/228848886-6e39fdb5-9356-428e-b41d-e5e4109f8ec4.png)

**Comment by guerrap** [comment]
There was also an issue when adding the `.` as the minimum bond in the creation form, the PR linked to this issue fixes both problems.
