### ISSUE TITLE
Campaign creation / more field validation

### ISSUE THREAD

**Issue by MilanVojnovic95** [carrot-kpi/erc20-kpi-token-template#90]
It's still possible to input "." or "@(#*$&**^%@#$" sybols in field and create campaign.

![Image](https://user-images.githubusercontent.com/57331244/228850412-be0eb7a3-fbdb-4977-9957-e33f33c6d485.png)

![Image](https://user-images.githubusercontent.com/57331244/228850113-d82df6b9-7562-4c99-a070-173b199fbb1a.png)

**Comment by guerrap** [comment]
This PR fixes a few issues and blocks any special for the ERC20 inputs, but I think we should leave the other inputs as it is, so with the possibility to add special chars. What do you think? @luzzif
